version: '3.1'

services:

  mysqldb:
    image: mysql:8.0.34
    container_name: mysqldb   
    volumes:
      - farmer-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Farmer
    networks:
        - internal

  farmer-be:
    container_name: farmer-be
    build:
      dockerfile: ./Dockerfile
      args:
        APP_NAME: nffh-farmer-BE
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Farmer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - gateway
      - internal
      - auth

networks:
  gateway:
    external: true
    name: g-farmer-be
  auth:
    external: true
    name: a-farmer-be
  internal:
    external: false


volumes:
  farmer-mysql-data:
      